services:
  chatwoot-base: &chatwoot-base
    image: chatwoot/chatwoot:v4.7.0
    env_file: .env
    volumes:
      - ./docker_data/storage:/app/storage
      - ./chatwoot_app/:/app 
    networks:
      - shared-net

  chatwoot-rails:
    <<: *chatwoot-base
    container_name: test-chatwoot-rails
    depends_on:
      - postgres
      - redis
    ports:
      - '0.0.0.0:3002:3002'
    environment:
      - CHATWOOT_BASE_URL=${CHATWOOT_BASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - FORCE_SSL=true
      - RAILS_FORCE_SSL=true
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#
      - FRONTEND_APP_TITLE=Connect
      - BRAND_NAME=Connect
      - INSTALLATION_NAME=Connect
      - DISPLAY_MANIFEST=false
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3002', '-b', '0.0.0.0']
    restart: always

  chatwoot-sidekiq:
    <<: *chatwoot-base
    container_name: test-chatwoot-sidekiq
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#
      - FRONTEND_APP_TITLE=Connect
      - BRAND_NAME=Connect
      - INSTALLATION_NAME=Connect
      - DISPLAY_MANIFEST=false
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  redis:
    image: redis:alpine
    container_name: test-chatwoot-redis
    restart: always
    networks:
      - shared-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server --requirepass "${REDIS_PASSWORD}" --port 6384 --appendonly yes
    volumes:
      - ./docker_data/redis:/data
    ports:
      - '127.0.0.1:6384:6384'
    env_file: .env

  postgres:
    container_name: test-chatwoot-postgres
    image: pgvector/pgvector:pg16
    restart: always
    networks:
      - shared-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    ports:
      - '127.0.0.1:5439:5432'
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    expose:
      - 5439

networks:
  shared-net:
    external: true
